#!/bin/bash

# emoji support requires ttf-font-awesome 5.15.3-1

case $BUTTON in
	1) notify-send "Battery Status" "Battery Status Information
: plugged in
: no battery
: battery charging
: battery full
: battery discharging";;

esac

plug=""
noBattery=""
fullBattery=""
chargBattery=""
disBattery=""

# Test for wall outlet plugin
ac="$(cat /sys/class/power_supply/AC/online)"
if [ $ac == "1" ]
then
	acOutput=$plug
else
	acOutput=""
fi

# Test for battery plug in
if [ -d "/sys/class/power_supply/BAT0/" ] 
then
	# battery plugged in
	batcapacity="$(cat /sys/class/power_supply/BAT0/capacity)"
	batstatus="$(cat /sys/class/power_supply/BAT0/status)"	
	[ $batstatus == "Full" ] && batOutput=$fullBattery
	[ $batstatus == "Charging" ] && batOutput=$chargBattery
	[ $batstatus == "Discharging" ] && batOutput=$disBattery
	batOutput=" $batOutput $batcapacity%"
else
	batOutput=""
fi

 printf "%s%s\n" "$acOutput" "$batOutput"
