#!/bin/bash

while test $# -gt 0; do
	case "$1" in
		-h|--help) 
			help="1"
			shift;;
		-b|--buildcache) 
			build="build"
			shift
			case "$1" in
				''|*[!0-9*)
					startfile=1;;
				*)
					startfile=$1
					shift;;
			esac
			;;
		-r|--rebuildcache) 
			build="rebuild"
			shift
			case "$1" in
				''|*[!0-9*)
					echo "rebuilding all"
					startfile=1;;
				*)
					echo "rebuilding from $1"
					startfile=$1
					shift;;
			esac
			;;
		*) 
			echo "unknown flag use --help for more info"
			exit 1;;
	esac
done

if [ "$help" == "1" ]
then
	echo "Locks screen, choosing a random background from ~/Wallpapers"
	echo " "
	echo "-b,  --buildcache    Build the cache, skipping windows that are already cached"
	echo "-r,  --rebuildcache  Build the entire cache of correctly sized windows"
	echo "                     If followed by a number, rebuild starts at that number"
	exit 0
fi 

resolution=$(xrandr | fgrep "*" | awk '{print $1}')

if [ "$build" == "build" ] || [ "$build" == "rebuild" ]
then
	
	fileCount=$(ls ~/Wallpapers | wc -l)
	currentfile=1

	echo "building cache"
	for file in ~/Wallpapers/*
	do 
		if [ $startfile -gt $currentfile ]; then
			currentfile=$(expr $currentfile + 1)
			continue
		fi		

		FileName=$(basename ${file//.jpg/.png})
		CacheFile=~/.Wallpapers_cache/LockScreens/$FileName

		if $(test -f "$CacheFile") && [ "$build" == "build" ]
		then
			echo [$currentfile/$fileCount] $(basename $file) found in cache
			currentfile=$(expr $currentfile + 1)
			continue
		fi

		echo [$currentfile/$fileCount] converting image $file to resolution: $resolution
		

		# echo $FileName
		convert $file -colorspace RGB -gravity center -resize $resolution^ -gravity center -crop $resolution+0+0 +repage PNG:- | convert - ~/.Wallpapers_cache/LockScreens/$FileName

		currentfile=$(expr $currentfile + 1)
	done
	exit 0
fi

file=$(ls ~/Wallpapers | shuf -n 1)
fullpath=~/.Wallpapers_cache/LockScreens/${file//.jpg/.png}

if test -f "$fullpath"; then
	echo "image found in cache $fullpath"
	i3lock --image $fullpath
	exit 0
fi

echo "image not in cache converting"
convert ~/Wallpapers/$file -colorspace RGB -resize "$resolution^" -gravity center -crop "$resolution" PNG:- | convert - $fullpath

echo "locking"
i3lock --image $fullpath
