#!/bin/dash

[ -d ~/myPhone ] && read -p "~/myPhone already exists, overwrite? [y/N]: " yn &&
case $yn in
	[Yy]*)rm -i -rd ~/myPhone;;
	*) echo "Aborted"; return 1;;
esac

mkdir ~/myPhone
jmtpfs ~/myPhone
